### ISSUE TITLE
[THANKS] Life saver! 

### ISSUE THREAD

**Issue by angelhdzmultimedia** [michealroberts/usetrpc#3]
I discovered **tRPC** today, and decided to try it, but the examples used _React_ or _Nuxt_... and I wanted to keep it simple using just Node/Express/TypeScript/Vue 3.

So found your package, and almost got discouraged by it because it failed to install via `npm i @trpc/vue`
and because the To Do says `useMutation `is coming later and not available at this time (now I realize it's another helper, the client already can call mutations).

But because there were only 2 files in the source code, and it wouldn't be a hassle, I decided to copy them to my client source code directly.
There were no errors, but I didn't get any output or change in the server or in the client.

After a while of toying around, I realized your package depends on `@trpc/client` and `@trpc/server`, so I installed them on my client's project folder (i have the server project as the root, so had to go 1 level down), and bam! It worked right away!!! 🤯😱🔥🎉👏🙌

So I appreciate it a lot because I usually get very anxious with configuring stuff even though I had a lot of experience programming (ActionScript 2.0/3.0, C#, Python, Dart, JS/TS) and I had no hopes on being able to use tRPC this early. I expected to wait few months or maybe 1-2 years until the usage of tRPC with `Vue `was more standard.

Would you check my repo to see if it's working as it should? I mean, to me it looks like it works.
Repo link: https://stackblitz.com/edit/node-pomdwu

Wishing you a lot of health and success.

**Comment by michealroberts** [comment]
@angelhdzmultimedia Hi Angel. Thqnk you very much for your kind comments. I'm so pleased the code worked for you, and apologies for the confusion!

The confusion is this package isn't quite ready yet, it's a work in progress. I'm aiming to have it ready within the next 2 - 3 weeks once I have the useQuery() composable battled tested and also unit tested! :)

Please star and follow, to get the latest updates.

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia Hi Angel. Thank you very much for your kind comments. I'm so pleased the code worked for you, and apologies for the confusion!
> 
> The confusion is this package isn't quite ready yet, it's a work in progress. I'm aiming to have it ready within the next 2 - 3 weeks once I have the useQuery() composable battled tested and also unit tested! :)
> 
> Please star and follow, to get the latest updates.
> 
> I will close this issue, as it's best to - but I really appreciate your kind words!

My apologizes for not closing it sooner! I usually close the issues when solved.  I probably was exited about being able to use this package right away after installing the dependencies, that I forgot to close it, LOL!

I'm also aware of the **Discusions** tab in Github, so instead of leaving "Issues", we can leave messages and have a conversation about it, but I didn't find that tab activated in your repo.

 Again, appreciate your time and your energy building this tool, and will keep following it and going deeper into tRPC.  And I hope this becomes the official client for working with Vue.
 
 Well, I won't take more of your time. Have a nice rest of the day.
