### ISSUE TITLE
OpenRPC: tRPC, ts-rest, zodios alternative now support vue query

### ISSUE THREAD

**Issue by dinwwwh** [michealroberts/usetrpc#8]
Seem this dead, so I think good if give dev more choices

https://github.com/unnoq/orpc

**Comment by michealroberts** [comment]
Hi @unnoq ... I'm not sure it is up to you to decide if something is dead or not, but this is incredibly disrespectful to do this to promote your own library/libraries.

Whilst I don't doubt your library is good, or perhaps better, please do not do this in future to mine, or others, libraries.

Perhaps, instead offer support for maintenance, or offer feature suggestions or improvements.

Thank you.

**Comment by dinwwwh** [comment]
I'm bad, sory

**Comment by michealroberts** [comment]
@unnoq No worries at all, apology accepted. And thank you for closing. My advise in future: reach out to me in person. I am human.

I will follow your library as it looks very interesting.

**Comment by dinwwwh** [comment]
Hi @michealroberts , Thank you for your kind words! When I read your reply to this issue, I realized my mistake. I’m very happy to see your interest in oRPC and truly appreciate your input.
